import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getQuote, getQuoteShare, getVehicleModel } from "@/lib/data";
import { CopyLinkButton } from "@/components/CopyLinkButton";
import { QuoteDocument } from "@/components/QuoteDocument";
import { SubmitButton } from "@/components/SubmitButton";
import { TruckElevation } from "@/components/TruckElevation";
import { TruckPreview } from "@/components/TruckPreview";
import {
  deleteQuoteAction,
  refineQuoteAction,
  saveSalesInfoAction,
  setQuoteShareAction,
  setQuoteStatusAction,
} from "@/app/actions";
import { isBlankSpec, normalizeBuildSpec } from "@/lib/spec";
import type { QuoteStatus } from "@/lib/types";

export const dynamic = "force-dynamic";

const STATUSES: QuoteStatus[] = ["draft", "revised", "sent", "accepted", "archived"];

export default async function QuoteDetailPage({
  params,
  searchParams,
}: {
  params: { id: string };
  searchParams: { error?: string };
}) {
  const quote = await getQuote(params.id);
  if (!quote) notFound();
  // Intake complete but quote not generated yet — review the spec first.
  if (!quote!.quote_data?.lineItems?.length) redirect(`/quotes/${params.id}/spec`);

  const [share, vehicle] = await Promise.all([
    getQuoteShare(params.id),
    quote!.vehicle_model_id ? getVehicleModel(quote!.vehicle_model_id) : Promise.resolve(null),
  ]);
  const spec = normalizeBuildSpec(quote!.build_spec, quote!.truck_type);
  const showTruck = !isBlankSpec(spec);

  return (
    <div className="space-y-6">
      <div className="no-print flex flex-wrap items-center justify-between gap-3">
        <Link href="/" className="text-sm text-zinc-400 hover:text-white">
          ← Dashboard
        </Link>
        <div className="flex items-center gap-2 text-xs text-zinc-500">
          Generated by{" "}
          <span className="rounded bg-white/5 px-2 py-0.5 font-medium text-zinc-300">
            {quote.ai_provider}
            {quote.ai_model ? ` · ${quote.ai_model}` : ""}
          </span>
        </div>
      </div>

      {searchParams.error ? (
        <div className="no-print rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">
          {searchParams.error}
        </div>
      ) : null}

      {showTruck ? (
        <div className="no-print">
          <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-zinc-400">
            Build preview — drag to rotate, scroll to zoom
          </h2>
          <TruckPreview
            spec={spec}
            vehicle={vehicle}
            className="h-96 w-full overflow-hidden rounded-xl border border-white/10 bg-[#101013]"
          />
          <div className="mt-3 rounded-xl border border-white/10 bg-white p-3">
            <TruckElevation spec={spec} vehicle={vehicle} />
          </div>
        </div>
      ) : null}

      <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
        {/* Document */}
        <div>
          <QuoteDocument quote={quote} />
        </div>

        {/* Control panel */}
        <aside className="no-print space-y-5">
          {/* Refine */}
          <Panel title="Refine this quote">
            <p className="mb-3 text-xs text-zinc-400">
              Anything to modify? Describe the change and the{" "}
              {quote.ai_provider === "sample" ? "estimator" : "AI"} will update the quote.
            </p>
            <form action={refineQuoteAction} className="space-y-3">
              <input type="hidden" name="quoteId" value={quote.id} />
              <textarea
                name="instruction"
                rows={4}
                required
                placeholder="e.g. Swap the 6-burner range for a flat-top griddle, add a second fryer, and drop the lead time to 8 weeks."
                className="w-full rounded-lg border border-white/12 bg-white/[0.03] px-3 py-2 text-sm text-zinc-100 outline-none placeholder:text-zinc-500 focus:border-amber-brand focus:ring-1 focus:ring-amber-brand"
              />
              <SubmitButton
                pendingLabel="Updating…"
                className="w-full rounded-md bg-amber-brand px-4 py-2 text-sm font-semibold text-black transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60"
              >
                Apply change
              </SubmitButton>
            </form>
          </Panel>

          {/* Sales notes & follow-up */}
          <Panel title="Sales notes & follow-up">
            <form action={saveSalesInfoAction} className="space-y-3">
              <input type="hidden" name="quoteId" value={quote.id} />
              <textarea
                name="sales_notes"
                rows={3}
                defaultValue={quote.sales_notes ?? ""}
                placeholder="Call summary, objections, next steps…"
                className="w-full rounded-lg border border-white/12 bg-white/[0.03] px-3 py-2 text-sm text-zinc-100 outline-none placeholder:text-zinc-500 focus:border-amber-brand"
              />
              <label className="block text-xs text-zinc-400">
                Follow up on
                <input
                  type="date"
                  name="follow_up_at"
                  defaultValue={quote.follow_up_at ? quote.follow_up_at.slice(0, 10) : ""}
                  className="mt-1 w-full rounded-md border border-white/12 bg-white/[0.03] px-2 py-1.5 text-sm text-zinc-100 outline-none focus:border-amber-brand"
                />
              </label>
              <SubmitButton
                pendingLabel="Saving…"
                className="w-full rounded-md bg-white/10 px-4 py-2 text-sm font-medium text-zinc-200 transition hover:bg-white/15"
              >
                Save sales info
              </SubmitButton>
            </form>
          </Panel>

          {/* Share with customer */}
          <Panel title="Share with customer">
            {share?.share_enabled ? (
              <div className="space-y-2">
                <p className="text-xs text-zinc-400">
                  Anyone with the link can view the quote and the 3D build preview
                  (read-only).
                </p>
                <CopyLinkButton path={`/q/${share.share_token}`} />
                <form action={setQuoteShareAction}>
                  <input type="hidden" name="quoteId" value={quote.id} />
                  <input type="hidden" name="enabled" value="false" />
                  <SubmitButton
                    pendingLabel="Disabling…"
                    className="w-full rounded-md bg-white/10 px-4 py-2 text-sm font-medium text-zinc-300 transition hover:bg-white/15"
                  >
                    Disable link
                  </SubmitButton>
                </form>
              </div>
            ) : (
              <div className="space-y-2">
                <p className="text-xs text-zinc-400">
                  Create a read-only link showing the customer their quote and what
                  the truck will look like.
                </p>
                <form action={setQuoteShareAction}>
                  <input type="hidden" name="quoteId" value={quote.id} />
                  <input type="hidden" name="enabled" value="true" />
                  <SubmitButton
                    pendingLabel="Creating link…"
                    className="w-full rounded-md bg-amber-brand px-4 py-2 text-sm font-semibold text-black transition hover:brightness-110"
                  >
                    Create shareable link
                  </SubmitButton>
                </form>
              </div>
            )}
          </Panel>

          {/* Build spec */}
          <Panel title="Build spec">
            <p className="mb-3 text-xs text-zinc-400">
              The structured spec extracted from the customer&apos;s documents. Lay it
              out in the builder, or edit fields directly.
            </p>
            <Link
              href={`/quotes/${quote.id}/builder`}
              className="mb-2 block w-full rounded-md bg-amber-brand px-4 py-2 text-center text-sm font-semibold text-black transition hover:brightness-110"
            >
              Open truck builder →
            </Link>
            <Link
              href={`/quotes/${quote.id}/spec`}
              className="block w-full rounded-md bg-white/10 px-4 py-2 text-center text-sm font-semibold text-white transition hover:bg-white/15"
            >
              View / edit build spec →
            </Link>
          </Panel>

          {/* Export */}
          <Panel title="Export">
            <Link
              href={`/quotes/${quote.id}/print`}
              className="block w-full rounded-md bg-white/10 px-4 py-2 text-center text-sm font-semibold text-white transition hover:bg-white/15"
            >
              Open PDF view →
            </Link>
            <Link
              href={`/quotes/${quote.id}/build-sheet`}
              className="mt-2 block w-full rounded-md bg-white/10 px-4 py-2 text-center text-sm font-semibold text-white transition hover:bg-white/15"
            >
              Shop build sheet →
            </Link>
          </Panel>

          {/* Status */}
          <Panel title="Status">
            <form action={setQuoteStatusAction} className="flex gap-2">
              <input type="hidden" name="quoteId" value={quote.id} />
              <select
                name="status"
                defaultValue={quote.status}
                className="flex-1 rounded-md border border-white/12 bg-white/[0.03] px-2 py-1.5 text-sm capitalize text-zinc-100 outline-none focus:border-amber-brand"
              >
                {STATUSES.map((s) => (
                  <option key={s} value={s} className="capitalize">
                    {s}
                  </option>
                ))}
              </select>
              <SubmitButton
                pendingLabel="…"
                className="rounded-md bg-white/10 px-3 py-1.5 text-sm font-medium text-white transition hover:bg-white/15"
              >
                Set
              </SubmitButton>
            </form>
          </Panel>

          {/* Revision history */}
          {quote.revisions?.length ? (
            <Panel title="Revision history">
              <ul className="space-y-2 text-xs">
                {quote.revisions
                  .slice()
                  .reverse()
                  .map((r, i) => (
                    <li key={i} className="border-l-2 border-amber-brand/50 pl-3">
                      <div className="text-zinc-300">{r.request}</div>
                      <div className="text-zinc-500">
                        {new Date(r.at).toLocaleString()}
                      </div>
                    </li>
                  ))}
              </ul>
            </Panel>
          ) : null}

          {/* Danger */}
          <form action={deleteQuoteAction}>
            <input type="hidden" name="quoteId" value={quote.id} />
            <SubmitButton
              pendingLabel="Deleting…"
              className="w-full rounded-md border border-red-500/30 bg-red-500/10 px-4 py-2 text-sm font-medium text-red-300 transition hover:bg-red-500/20 disabled:opacity-60"
            >
              Delete quote
            </SubmitButton>
          </form>
        </aside>
      </div>
    </div>
  );
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-white/10 bg-ink-soft/60 p-4">
      <h3 className="mb-3 text-sm font-semibold text-white">{title}</h3>
      {children}
    </div>
  );
}
